/*
 * This source file was generated by the Gradle 'init' task
 *//*

package org.example;

public class App01 {
    public String getGreeting01() {
        return "01 , Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App01().getGreeting01());
    }
}
*/
